# Generated by Django 5.1.15 on 2026-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('role_dans_projet', models.CharField(blank=True, max_length=50, verbose_name='Rôle dans le projet')),
            ],
            options={
                'verbose_name': 'Membre du projet',
                'verbose_name_plural': 'Membres du projet',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé'), ('SUSPENDU', 'Suspendu')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('couleur', models.CharField(default='#1a3a6b', help_text='Code couleur hexadécimal (ex: #1a3a6b)', max_length=7, verbose_name='Couleur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image du projet')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
