# Generated by Django 5.1.15 on 2026-03-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membreprojet',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions_projets', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='projet',
            name='createur',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Professeur responsable'),
        ),
        migrations.AddField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='projets_membres', through='projects.MembreProjet', to=settings.AUTH_USER_MODEL, verbose_name="Membres de l'équipe"),
        ),
        migrations.AddField(
            model_name='membreprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='projects.projet', verbose_name='Projet'),
        ),
        migrations.AlterUniqueTogether(
            name='membreprojet',
            unique_together={('projet', 'utilisateur')},
        ),
    ]
