# Generated by Django 5.1.15 on 2026-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la tâche')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_REVISION', 'En révision'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='A_FAIRE', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('date_limite', models.DateTimeField(help_text='Date et heure limite pour terminer cette tâche', verbose_name='Date limite')),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion réelle')),
                ('termine_dans_delais', models.BooleanField(blank=True, help_text='Automatiquement défini lors de la complétion', null=True, verbose_name='Terminé dans les délais')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('etiquettes', models.CharField(blank=True, help_text='Séparées par des virgules (ex: frontend,urgent,design)', max_length=200, verbose_name='Étiquettes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['ordre', 'date_limite', '-priorite'],
            },
        ),
    ]
