# Generated by Django 5.1.15 on 2026-03-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairetache',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_taches', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ETUDIANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='tache',
            name='cree_par',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='taches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='commentairetache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='tasks.tache', verbose_name='Tâche'),
        ),
    ]
